In [7]:

import torch

bs = 4
max_time = 5
max_length = 10
audio_len = torch.tensor([1, 2, 3, 4])
audio_mask = torch.arange(max_time)[None, :] < audio_len[:, None] 

mask2 = audio_mask[:, None, :] & audio_mask[:, :, None]

attention_mask = torch.tril(torch.ones((max_length, max_length))).unsqueeze(0)
attention_mask = attention_mask < 0.5
attention_mask = attention_mask.repeat(bs, 1, 1, 1)



In [4]:
print(mask2[0].shape)
print(mask2[0])

torch.Size([5, 5])
tensor([[ True, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [5]:
print(audio_mask[0].shape)
print(audio_mask[0])

torch.Size([5])
tensor([ True, False, False, False, False])


In [9]:
attention_mask[0]

tensor([[[False,  True,  True,  True,  True,  True,  True,  True,  True,  True],
         [False, False,  True,  True,  True,  True,  True,  True,  True,  True],
         [False, False, False,  True,  True,  True,  True,  True,  True,  True],
         [False, False, False, False,  True,  True,  True,  True,  True,  True],
         [False, False, False, False, False,  True,  True,  True,  True,  True],
         [False, False, False, False, False, False,  True,  True,  True,  True],
         [False, False, False, False, False, False, False,  True,  True,  True],
         [False, False, False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False, False, False, False,  True],
         [False, False, False, False, False, False, False, False, False, False]]])

In [13]:
audio_mask2 = audio_mask.unsqueeze(1).unsqueeze(-1)
audio_mask2.shape

torch.Size([4, 1, 5, 1])

In [14]:
attention_mask[:, :, :max_time, :] &= audio_mask2

In [15]:
attention_mask[0]

tensor([[[False,  True,  True,  True,  True,  True,  True,  True,  True,  True],
         [False, False, False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False, False, False, False, False],
         [False, False, False, False, False, False,  True,  True,  True,  True],
         [False, False, False, False, False, False, False,  True,  True,  True],
         [False, False, False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False, False, False, False,  True],
         [False, False, False, False, False, False, False, False, False, False]]])